### ISSUE TITLE
relative paths

### ISSUE THREAD

**Issue by kbilsted** [nemec/pathlib#5]
Thanks for the library. Just found it after having looked for such a library in some time.

What are your thoughts on supporting relative paths?

**Comment by nemec** [comment]
Hi @kbilsted, is there anything in particular that you would like support for? It already has some support for relative paths:

	var rel = PurePath.Create("documents/code");
	Console.WriteLine(rel.IsAbsolute());

> False
	
	var root = PurePath.Create("C:\\Users");
	var abs = PurePath.Create("C:\\Users\\Administrator");
	
	var relTo = abs.RelativeTo(root);
	Console.WriteLine(relTo.ToString());

> Administrator

	Console.WriteLine(relTo.IsAbsolute());

> False
	
	Console.WriteLine(abs.Relative().ToString());

> Users\Administrator

**Comment by kbilsted** [comment]
Thanks for the examples. What is the type of "rel" …?

I'm thinking there might be value in specifying that a method takes or produces a relative or incomplete path. Perhaps it's just me but for the moment I'm in a phase where I cherish descriptive signatures using types. But maybe it's a can of worms we are opening. The api becomes more complex and a relative or partial path can either be a file system or network address..

**Comment by nemec** [comment]
Ah, I think I see what you mean. You're wondering if relative/absolute is baked into the type signature? No, it isn't. The type of `rel` above is an `IPurePath` since it's coming from the PurePath factory, but its actual type is `PureWindowsPath`. Nothing other properties of the path aside from the OS are included in the type. And even then, I highly recommend *not* relying on the particular implementation and instead use the interfaces `IPath` and `IPurePath` which allows you to be cross platform.

I do see where you're coming from, but then where do you stop? One of the most obvious candidates (that I began implementing, but had to undo) is a separate class for directories and files, since those are two totally different things. However, with a PurePath (which represents a path that may not even *exist* yet) it's impossible to tell whether it should be a directory or file "object" (I found that requiring a trailing slash for directories doesn't pass the "principle of least surprise").

**Comment by kbilsted** [comment]
Well, when things are hard, they tend to get interesting ;) I think that the raison d'être for your application is to rid `string` and introduce domain types. I welcome that. I understand your struggles with having modelled files and folders but not being able to ensure consistency in the constructor. Still methods like create, exist and delete are different for the two implementations as eg. deleting a folder requires deleting all files of the folder. 

Perhaps subinterfaces of `IPath` representing files and folders are a way to go. 

Perhaps a richer model than just files and folders are in order. Sometimes you have 

* A partial path
* A file without extension
* A file extension

You, as the general library provider, should not be the limiting factor in what I as a user can express. But supply entities for concepts are commonly recurring in projects.

Anyway regard this as a chip in to the grander debate. I hope we can keep the ball rolling just for a bit longer.

**Comment by nemec** [comment]
Great perspective, thanks for sharing. You're definitely right that files and directories have totally different implementations for create, etc. Internally we simply do this kind of thing, which breaks various "rules" of OOP: `If(IsDir()){DoDirectory();} else{DoFile();}`.

Given your input, I am going to put the idea of adding sub-interfaces on the TODO list however I don't think it's possible to merge the implementation of the normal, naive path classes with self-aware classes for one simple reason: an `IPath` can represent a path that *does not yet exist*. Without explicit guidance from the user of the API, you can't guarantee ahead of time whether a path will be a dir or a file. I suppose there could be a concept of an "indeterminate" path, but C# doesn't have any way for the instance to replace itself once it becomes clear which type you have.

Thanks again!

**Comment by kbilsted** [comment]
Why is that a problem? The only problem as I see it is that you cannot necessarily do the validations you wish in the constructor.

Perhaps a better approach is to start fresh on a new project if you think this is a shift of perspective. I'd happily join in. See I'm not convinced that the path can do all sorts of stuff. I'd rather have another directory and file abstraction (non-static of course) that mimics the existing api. More testable and more familiar to programmers. But I may well be going out on a limb here as I have yet to grok the code..

**Comment by kbilsted** [comment]
Are you familiar with https://github.com/psmacchia/NDepend.Path

**Comment by nemec** [comment]
I've heard of the first one, but the second is new to me. I notice that NDepend.Path doesn't support Linux-style paths, which is critical going forward given that .Net has begun focusing on cross-platform and CoreCLR in particular.

System.IO.Abstractions looks fantastic. What a great idea.

**Comment by kbilsted** [comment]
A few months back I couldn't find any of this. Then I found yours on reddit and it took off from there. I better blog about this at www.firstclassthoughts.co.UK :)
